name: Kubernetes Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select Environment
        options:
        - staging
        - production
jobs:
  publishimages:
    uses: ./.github/workflows/publish_docker_images.yaml
    name: Publish Images
    secrets:
      GOOGLE_PROJECT_NAME: ${{ secrets.GOOGLE_PROJECT_NAME }}
      GOOGLE_SERVICE_ACCOUNT_ENCODED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ENCODED }}

  Production-Deploy-Azure-Kubernetes:
    runs-on: ubuntu-latest
    needs: [publishimages]
    environment: ${{ github.event.inputs.environment }}
    if: "github.event.inputs.environment == 'production'"
    env:
      CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
      DIFFGRAM_SYSTEM_MODE: ${{ secrets.DIFFGRAM_SYSTEM_MODE }}
      EMAIL_VALIDATION: ${{ secrets.EMAIL_VALIDATION }}
      HUB_SPOT_KEY: ${{ secrets.HUB_SPOT_KEY }}
      INTER_SERVICE_SECRET: ${{ secrets.INTER_SERVICE_SECRET }}
      MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
      ML__CLOUD_STORAGE_BUCKET: ${{ secrets.ML__CLOUD_STORAGE_BUCKET }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      USER_PASSWORDS_SECRET: ${{ secrets.USER_PASSWORDS_SECRET }}
      _ANALYTICS_WRITE_KEY: ${{ secrets._ANALYTICS_WRITE_KEY }}
      DIFFGRAM_STATIC_STORAGE_PROVIDER: ${{ secrets.DIFFGRAM_STATIC_STORAGE_PROVIDER }}
      SERVICE_ACCOUNT_FULL_PATH: ${{ secrets.SERVICE_ACCOUNT_FULL_PATH }}
      FERNET_KEY: ${{ secrets.FERNET_KEY }}
      URL_BASE: ${{ secrets.URL_BASE }}
      WALRUS_SERVICE_URL_BASE: ${{ secrets.WALRUS_SERVICE_URL_BASE }}
      PROCESS_MEDIA_TRY_BLOCK_ON: ${{ secrets.PROCESS_MEDIA_TRY_BLOCK_ON }}
      PROCESS_MEDIA_REMOTE_QUEUE_ON: ${{ secrets.PROCESS_MEDIA_REMOTE_QUEUE_ON }}
      PROCESS_MEDIA_ENQUEUE_LOCALLY_IMMEDIATELY: ${{ secrets.PROCESS_MEDIA_ENQUEUE_LOCALLY_IMMEDIATELY }}
      WEBHOOKS_URL_BASE: ${{ secrets.WEBHOOKS_URL_BASE }}
      GOOGLE_SERVICE_ACCOUNT_ENCODED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ENCODED }}
      GOOGLE_APPLICATION_CREDENTIALS: ~/gcloud-service-key.json
      DOCKER_IMAGE_PROJECT_NAME: ${{ secrets.DOCKER_IMAGE_PROJECT_NAME }}
      GCR_CREDENTIALS_ENTERPRISE: ${{ secrets.GCR_CREDENTIALS_ENTERPRISE }}
      DIFFGRAM_INSTALL_FINGERPRINT: ${{ secrets.DIFFGRAM_INSTALL_FINGERPRINT }}
      DIFFGRAM_VERSION_TAG: ${{ github.event.inputs.release }}
      DIFFGRAM_HOST_OS: ${{ secrets.DIFFGRAM_HOST_OS }}
      DATABASE_CONNECTION_POOL_SIZE: ${{ secrets.DATABASE_CONNECTION_POOL_SIZE }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      EMAIL_DOMAIN_NAME: ${{ secrets.EMAIL_DOMAIN_NAME }}
      ALLOW_EVENTHUB: ${{ secrets.ALLOW_EVENTHUB }}
      IS_OPEN_SOURCE: ${{ secrets.IS_OPEN_SOURCE }}
      ALLOW_STRIPE_BILLING: ${{ secrets.ALLOW_STRIPE_BILLING }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}

      - name: Clone Helm Chart for Diffgram
        uses: actions/checkout@master
        with:
          repository: diffgram/diffgram-helm
      - name: Create Diffgram Version Production From Tag or Branch
        run: |
          echo "diffgram_version=new-relic-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Prepare app.yaml for helm chart.
        uses: microsoft/variable-substitution@v1
        with:
          files: 'values.yaml'
        env:
          diffgramVersion: ${{ env.diffgram_version }}
          diffgramEdition: opencore
          diffgramDomain: diffgram.com
          useCertManager: true
          useTls: true
          dbSettings.dbProvider: azure
          dbSettings.azureSqlEndpoint: ${{secrets.AZURE_SQL_ENDPOINT}}
          dbSettings.dbUser: ${{secrets.AZURE_DB_USER}}
          dbSettings.dbName: ${{secrets.AZURE_DB_NAME}}
          dbSettings.dbPassword: ${{secrets.AZURE_DB_PASSWORD}}
          diffgramSecrets.STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
          diffgramSecrets._ANALYTICS_WRITE_KEY: ${{secrets._ANALYTICS_WRITE_KEY}}
          diffgramSecrets.MAILGUN_KEY: ${{secrets.MAILGUN_KEY}}
          diffgramSecrets.HUB_SPOT_KEY: ${{secrets.HUB_SPOT_KEY}}
          diffgramSecrets.SECRET_KEY: ${{secrets.SECRET_KEY}}
          diffgramSecrets.FERNET_KEY: ${{secrets.FERNET_KEY}}
          diffgramSecrets.INTER_SERVICE_SECRET: ${{secrets.INTER_SERVICE_SECRET}}
          diffgramSecrets.USER_PASSWORDS_SECRET: ${{secrets.USER_PASSWORDS_SECRET}}
          diffgramSecrets.SERVICE_ACCOUNT_JSON_B64: ${{secrets.SERVICE_ACCOUNT_JSON_B64}}
          diffgramSecrets.DIFFGRAM_AZURE_CONNECTION_STRING: ${{secrets.DIFFGRAM_AZURE_CONNECTION_STRING}}
          diffgramSettings.USERDOMAIN: kubernetes_production
          diffgramSettings.DIFFGRAM_SYSTEM_MODE: production
          diffgramSettings.DIFFGRAM_STATIC_STORAGE_PROVIDER: azure
          diffgramSettings.DIFFGRAM_AZURE_CONTAINER_NAME: ${{secrets.DIFFGRAM_AZURE_CONTAINER_NAME}}
          diffgramSettings.ML__DIFFGRAM_AZURE_CONTAINER_NAME: ${{secrets.ML__DIFFGRAM_AZURE_CONTAINER_NAME}}
          diffgramSettings.WALRUS_SERVICE_URL_BASE: ${{secrets.WALRUS_SERVICE_URL_BASE}}
          diffgramSettings.DIFFGRAM_INSTALL_FINGERPRINT: ${{secrets.DIFFGRAM_INSTALL_FINGERPRINT}}
          diffgramSettings.DIFFGRAM_HOST_OS: ${{secrets.DIFFGRAM_HOST_OS}}
          diffgramSettings.DIFFGRAM_VERSION_TAG: ${{secrets.DIFFGRAM_VERSION_TAG}}
          diffgramSettings.DATABASE_CONNECTION_POOL_SIZE: ${{secrets.DATABASE_CONNECTION_POOL_SIZE}}
          diffgramSettings.PROCESS_MEDIA_NUM_VIDEO_THREADS: ${{secrets.PROCESS_MEDIA_NUM_VIDEO_THREADS}}
          diffgramSettings.PROCESS_MEDIA_NUM_FRAME_THREADS: ${{secrets.PROCESS_MEDIA_NUM_FRAME_THREADS}}
          diffgramSettings.NEW_RELIC_LICENSE_KEY: ${{secrets.NEW_RELIC_LICENSE_KEY}}
          diffgramSettings.EMAIL_DOMAIN_NAME: ${{secrets.EMAIL_DOMAIN_NAME}}
          diffgramSettings.ALLOW_EVENTHUB: ${{secrets.ALLOW_EVENTHUB}}
          diffgramSettings.EMAIL_VALIDATION: ${{secrets.EMAIL_VALIDATION}}
          diffgramSettings.IS_OPEN_SOURCE: ${{secrets.IS_OPEN_SOURCE}}
          diffgramSettings.ALLOW_STRIPE_BILLING: ${{secrets.ALLOW_STRIPE_BILLING}}
          imagePullCredentials.gcrCredentials: ${{secrets.GCR_CREDENTIALS_ENTERPRISE}}
          walrusService.requests.memory: "32G"
          walrusService.limits.memory: "32G"
          walrusService.requests.cpu: "8"
          walrusService.limits.cpu: "8"
          defaultService.requests.memory: "4G"
          defaultService.requests.cpu: "2"
          frontendService.requests.memory: "2G"
          frontendService.requests.cpu: "1"
          defaultService.numReplicas: 3
          frontendService.numReplicas: 1
          walrusService.numReplicas: 1
          nodeGroupLabel: diffgram-apps

      - name: Check values.yaml
        run: cat values.yaml


      # Set the target Azure Kubernetes Service (AKS) cluster.
      - name: Set Kubernetes Cluster Context on AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_CLUSTER_RESOURCE_GROUP }}


      - name: Upgrade Diffgram with Helm
        run: |
          helm upgrade --install diffgram . -f values.yaml --namespace diffgram-production


  Staging-Deploy-Azure-Kubernetes:
    runs-on: ubuntu-latest
    needs: [publishimages]
    environment: ${{ github.event.inputs.environment }}
    if: "github.event.inputs.environment == 'staging'"
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLOUD_STORAGE_BUCKET: ${{ secrets.CLOUD_STORAGE_BUCKET }}
      DIFFGRAM_SYSTEM_MODE: ${{ secrets.DIFFGRAM_SYSTEM_MODE }}
      EMAIL_VALIDATION: ${{ secrets.EMAIL_VALIDATION }}
      HUB_SPOT_KEY: ${{ secrets.HUB_SPOT_KEY }}
      INTER_SERVICE_SECRET: ${{ secrets.INTER_SERVICE_SECRET }}
      MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
      ML__CLOUD_STORAGE_BUCKET: ${{ secrets.ML__CLOUD_STORAGE_BUCKET }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      USER_PASSWORDS_SECRET: ${{ secrets.USER_PASSWORDS_SECRET }}
      _ANALYTICS_WRITE_KEY: ${{ secrets._ANALYTICS_WRITE_KEY }}
      DIFFGRAM_STATIC_STORAGE_PROVIDER: ${{ secrets.DIFFGRAM_STATIC_STORAGE_PROVIDER }}
      SERVICE_ACCOUNT_FULL_PATH: ${{ secrets.SERVICE_ACCOUNT_FULL_PATH }}
      FERNET_KEY: ${{ secrets.FERNET_KEY }}
      URL_BASE: ${{ secrets.URL_BASE }}
      WALRUS_SERVICE_URL_BASE: ${{ secrets.WALRUS_SERVICE_URL_BASE }}
      PROCESS_MEDIA_TRY_BLOCK_ON: ${{ secrets.PROCESS_MEDIA_TRY_BLOCK_ON }}
      PROCESS_MEDIA_REMOTE_QUEUE_ON: ${{ secrets.PROCESS_MEDIA_REMOTE_QUEUE_ON }}
      PROCESS_MEDIA_ENQUEUE_LOCALLY_IMMEDIATELY: ${{ secrets.PROCESS_MEDIA_ENQUEUE_LOCALLY_IMMEDIATELY }}
      WEBHOOKS_URL_BASE: ${{ secrets.WEBHOOKS_URL_BASE }}
      GOOGLE_SERVICE_ACCOUNT_ENCODED: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_ENCODED }}
      GOOGLE_APPLICATION_CREDENTIALS: ~/gcloud-service-key.json
      DOCKER_IMAGE_PROJECT_NAME: ${{ secrets.DOCKER_IMAGE_PROJECT_NAME }}
      GCR_CREDENTIALS_ENTERPRISE: ${{ secrets.GCR_CREDENTIALS_ENTERPRISE }}
      DATABASE_CONNECTION_POOL_SIZE: ${{ secrets.DATABASE_CONNECTION_POOL_SIZE }}
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
      EMAIL_DOMAIN_NAME: ${{ secrets.EMAIL_DOMAIN_NAME }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      ALLOW_EVENTHUB: ${{ secrets.ALLOW_EVENTHUB }}
      IS_OPEN_SOURCE: ${{ secrets.IS_OPEN_SOURCE }}
      ALLOW_STRIPE_BILLING: ${{ secrets.ALLOW_STRIPE_BILLING }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - run: |
          ls -a ./
          echo "----"
          ls -a ./.github
          echo "----"
          ls -a ./.github/workflows
          echo "----"
          cd ./.github/workflows
          pwd
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}

      - name: Clone Helm Chart for Diffgram
        uses: actions/checkout@master
        with:
          repository: diffgram/diffgram-helm

      - name: Create Diffgram Version Production From Tag or Branch
        run: |
          echo "diffgram_version=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 30

      - name: Prepare app.yaml for helm chart.
        uses: microsoft/variable-substitution@v1
        with:
          files: 'values.yaml'
        env:
          diffgramVersion: ${{ env.diffgram_version }}
          diffgramEdition: opencore
          diffgramDomain: ${{ env.GITHUB_REF_SLUG }}.dataannotation.info
          useCertManager: true
          useTls: true
          dbSettings.dbProvider: azure
          dbSettings.azureSqlEndpoint: ${{secrets.AZURE_SQL_ENDPOINT}}
          dbSettings.dbUser: ${{secrets.AZURE_DB_USER}}
          dbSettings.dbName: ${{secrets.AZURE_DB_NAME}}
          dbSettings.dbPassword: ${{secrets.AZURE_DB_PASSWORD}}
          diffgramSecrets.STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
          diffgramSecrets._ANALYTICS_WRITE_KEY: ${{secrets._ANALYTICS_WRITE_KEY}}
          diffgramSecrets.MAILGUN_KEY: ${{secrets.MAILGUN_KEY}}
          diffgramSecrets.HUB_SPOT_KEY: ${{secrets.HUB_SPOT_KEY}}
          diffgramSecrets.SECRET_KEY: ${{secrets.SECRET_KEY}}
          diffgramSecrets.INTER_SERVICE_SECRET: ${{secrets.INTER_SERVICE_SECRET}}
          diffgramSecrets.USER_PASSWORDS_SECRET: ${{secrets.USER_PASSWORDS_SECRET}}
          diffgramSecrets.SERVICE_ACCOUNT_JSON_B64: ${{secrets.SERVICE_ACCOUNT_JSON_B64}}
          diffgramSecrets.DIFFGRAM_AZURE_CONNECTION_STRING: ${{secrets.DIFFGRAM_AZURE_CONNECTION_STRING}}
          diffgramSettings.USERDOMAIN: kubernetes_production
          diffgramSettings.DIFFGRAM_SYSTEM_MODE: production
          diffgramSettings.DIFFGRAM_STATIC_STORAGE_PROVIDER: azure
          diffgramSettings.WALRUS_SERVICE_URL_BASE: ${{secrets.WALRUS_SERVICE_URL_BASE}}
          diffgramSettings.DIFFGRAM_AZURE_CONTAINER_NAME: staging1
          diffgramSettings.ML__DIFFGRAM_AZURE_CONTAINER_NAME: staging1
          diffgramSettings.DIFFGRAM_INSTALL_FINGERPRINT: ${{secrets.DIFFGRAM_INSTALL_FINGERPRINT}}
          diffgramSettings.DIFFGRAM_HOST_OS: ${{secrets.DIFFGRAM_HOST_OS}}
          diffgramSettings.DIFFGRAM_VERSION_TAG: ${{secrets.DIFFGRAM_VERSION_TAG}}
          diffgramSettings.DATABASE_CONNECTION_POOL_SIZE: ${{secrets.DATABASE_CONNECTION_POOL_SIZE}}
          diffgramSettings.PROCESS_MEDIA_NUM_VIDEO_THREADS: ${{secrets.PROCESS_MEDIA_NUM_VIDEO_THREADS}}
          diffgramSettings.PROCESS_MEDIA_NUM_FRAME_THREADS: ${{secrets.PROCESS_MEDIA_NUM_FRAME_THREADS}}
          diffgramSettings.NEW_RELIC_LICENSE_KEY: ${{secrets.NEW_RELIC_LICENSE_KEY}}
          diffgramSettings.EMAIL_DOMAIN_NAME: ${{secrets.EMAIL_DOMAIN_NAME}}
          diffgramSettings.ALLOW_EVENTHUB: ${{secrets.ALLOW_EVENTHUB}}
          diffgramSettings.EMAIL_VALIDATION: ${{secrets.EMAIL_VALIDATION}}
          diffgramSettings.IS_OPEN_SOURCE: ${{secrets.IS_OPEN_SOURCE}}
          diffgramSettings.ALLOW_STRIPE_BILLING: ${{secrets.ALLOW_STRIPE_BILLING}}
          imagePullCredentials.gcrCredentials: ${{secrets.GCR_CREDENTIALS_ENTERPRISE}}
          defaultService.numReplicas: 1
          frontendService.numReplicas: 1
          walrusService.numReplicas: 1
          defaultService.requests.cpu: "1"
          defaultService.requests.memory: "1G"
          defaultService.limits.cpu: "1"
          defaultService.limits.memory: "1G"
          frontendService.requests.cpu: "1"
          frontendService.requests.memory: "1G"
          frontendService.limits.cpu: "1"
          frontendService.limits.memory: "1G"
          walrusService.requests.cpu: "1"
          walrusService.requests.memory: "1G"
          walrusService.limits.cpu: "1"
          walrusService.limits.memory: "1G"
          nodeGroupLabel: null

      - name: Check values.yaml
        run: cat values.yaml


      # Set the target Azure Kubernetes Service (AKS) cluster.
      - name: Set Kubernetes Cluster Context on AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_CLUSTER_RESOURCE_GROUP }}


      - name: Upgrade Diffgram with Helm
        run: |
          helm upgrade --install diffgram . -f values.yaml --namespace diffgram-staging
